[metadata]
name = ogrre_embed
version = 0.1.0
author = OGRRE Team
description = Package for embedding searchable text into PDFs using Document AI OCR layout data
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT

[options]
packages = find:
py_modules =
    ogrre_embed
    gcs_storage_utils
python_requires = >=3.8
install_requires =
    PyMuPDF>=1.24.0
    google-cloud-storage
    tqdm

[options.packages.find]
where = .
