[metadata]
name = ogrre_embed
version = 0.1.0
author = OGRRE Team
description = Package for embedding searchable text into PDFs using Document AI OCR layout data
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.8
install_requires =
    PyMuPDF>=1.24.0
    google-cloud-storage
    tqdm

[options.packages.find]
where = src
